openapi: 3.0.3
info:
  title: Guest API
  version: 1.0.0
  description: API for managing guests
  contact:
    name: Gabriel Arrighi Silva
    email: gasilva912@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://api.fiap.com.br/guest
    description: Production server
tags:
  - name: Guest
    description: Operations related to guests
paths:
  /guest:
    get:
      tags:
        - Guest
      summary: List all guests
      operationId: listGuests
      responses:
        "200":
          description: A list of guests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Guest"
    post:
      tags:
        - Guest
      summary: Create a new guest
      operationId: createGuest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateGuest"
      responses:
        "201":
          description: The guest was created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Guest"
  /guest/{guestId}:
    get:
      tags:
        - Guest
      summary: Get a guest by ID
      operationId: getGuest
      parameters:
        - name: guestId
          in: path
          description: ID of the guest to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Guest found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Guest"
        "404":
          description: Guest not found
    put:
      tags:
        - Guest
      summary: Update an existing guest
      operationId: updateGuest
      parameters:
        - name: guestId
          in: path
          description: The guest ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateGuest"
      responses:
        "200":
          description: The guest was updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Guest"
    delete:
      tags:
        - Guests
      summary: Delete a guest
      operationId: deleteGuest
      parameters:
        - name: guestId
          in: path
          description: The guest ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: The guest was deleted
components:
  schemas:
    Guest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The guest ID
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          maxLength: 255
          description: The guest name
          example: John Doe
        email:
          type: string
          format: email
          maxLength: 255
          description: The guest email
          example: guest@email.com
        createdAt:
          type: string
          format: date-time
          description: The date and time the guest was created
          example: 2021-06-01T10:00:00Z
        updatedAt:
          type: string
          format: date-time
          description: The date and time the guest was updated
          example: 2021-06-01T10:00:00Z
        deletedAt:
          type: string
          format: date-time
          description: The date and time the guest was deleted
          example: 2021-06-01T10:00:00Z
    CreateGuest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: The guest name
          example: John Doe
        email:
          type: string
          format: email
          description: The guest email
          maxLength: 255
          example: guest@email.com
        password:
          type: string
          format: password
          description: The guest password
          maxLength: 255
          example: password
      required:
        - name
        - email
        - password
    UpdateGuest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: The guest name
          example: John Doe
        email:
          type: string
          format: email
          description: The guest email
          maxLength: 255
          example: guest@email.com
        password:
          type: string
          format: password
          description: The guest password
          maxLength: 255
          example: password
