openapi: 3.0.3
info:
  title: Login API
  version: 1.0.0
  description: API for login in system
  contact:
    name: Gabriel Arrighi Silva
    email: gasilva912@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://api.fiap.com.br/login
    description: Production server
tags:
  - name: Login
    description: Operations related to login
paths:
  /login:
    post:
      tags:
        - Login
      summary: Login in system
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestLogin"
      responses:
        "201":
          description: The login was successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
components:
  schemas:
    Login:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The user or guest ID
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          maxLength: 255
          description: The user or guest name
          example: John Doe
        email:
          type: string
          format: email
          maxLength: 255
          description: The user or guest email
          example: user@email.com
        isGuest:
          type: boolean
          description: Indicates if the user is a guest
          example: false
        createdAt:
          type: string
          format: date-time
          description: The date and time the user or guest was created
          example: 2021-06-01T10:00:00Z
        updatedAt:
          type: string
          format: date-time
          description: The date and time the user or guest was updated
          example: 2021-06-01T10:00:00Z
        deletedAt:
          type: string
          format: date-time
          description: The date and time the user or guest was deleted
          example: 2021-06-01T10:00:00Z
    RequestLogin:
      type: object
      properties:
        email:
          type: string
          format: email
          description: The user or guest email
          maxLength: 255
          example: user@email.com
        password:
          type: string
          format: password
          description: The user or guest password
          maxLength: 255
          example: password
      required:
        - email
        - password
